layer:
  id: "powerline"
  description: |
      **power** contains power related items
  buffer_size: 4
  srs: +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over
  fields:
    name: The OSM [`name`](http://wiki.openstreetmap.org/wiki/Key:name) value of the powerline.
    class:
      description: |
          Power transmittions lines (cable, line, minor_line, minor_cable
          [`power`](http://wiki.openstreetmap.org/wiki/Key:power) tag.
      values:
      - cable
      - line
      - minor_line
      - minor_cable 
  datasource:
    geometry_field: geometry
    srid: 900913
    query: (SELECT geometry, class, name FROM layer_powerline(!bbox!, z(!scale_denominator!))) AS t
schema:
  - ./powerline.sql
datasources:
  - type: imposm3
    mapping_file: ./powerline-mapping.yaml
