# Workflow to run basic integrity checks on OMT`s new Pull Requests and commits pushed into OMT repo

name: OpenMapTiles Integrity CI

on:
  push:
    branches: [ master, master-tools ]
  pull_request:

jobs:

  integrity_test:
    name: Run integrity test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the changes
        uses: actions/checkout@v2

      - name: Run quickstart for a small area
        env:
          area: monaco
          QUIET: 1
        run: |
          echo MIN_ZOOM=0 >> .env
          echo MAX_ZOOM=14 >> .env
          ./quickstart.sh $area

      - name: Save quickstart.log
        uses: actions/upload-artifact@v2
        with:
          name: quickstart.log
          path: quickstart.log

      - name: Test etldoc images
        run: |
          export TEST_MODE=yes
          make generate-devdoc
